### ISSUE TITLE
nnetsauce and R

### ISSUE THREAD

**Issue by samilotin** [Techtonique/nnetsauce#21]
* nnetsauce version: 0.10.0
* Python version: python 3.8
* Operating System: mac OS Big Sur 11.6.4

### Description

Installation in R

Impossible to install nnetsauce in R

### What I Did

python installed via reticulate : /Users/my_name/Library/r-miniconda/envs/r-reticulate/lib/python3.8

'''
> library(devtools)
Le chargement a nécessité le package : usethis
> devtools::install_github("Techtonique/nnetsauce/R-package")
Downloading GitHub repo Techtonique/nnetsauce@HEAD
✓  checking for file ‘/private/var/folders/s3/ryybwwrx7cld88lzkc52k9p00000gn/T/Rtmp1dUDN7/remotes12ec39537652/Techtonique-nnetsauce-6145d52/R-package/DESCRIPTION’ ...
─  preparing ‘nnetsauce’:
✓  checking DESCRIPTION meta-information ...
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
   Omitted ‘LazyData’ from DESCRIPTION
─  building ‘nnetsauce_0.10.0.tar.gz’
   
* installing *source* package ‘nnetsauce’ ...
** using staged installation
** R
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded from temporary location
WARNING: Skipping nnetsauce as it is not installed.
Activated conda python: /Users/my_name/Library/r-miniconda/envs/r-reticulate/bin/python
Requirement already satisfied: numpy in /Users/frederic/Library/r-miniconda/envs/r-reticulate/lib/python3.8/site-packages (1.22.2)
Activated conda python: /Users/my_name/Library/r-miniconda/envs/r-reticulate/bin/python
Collecting rpy2
  Using cached rpy2-3.4.5-cp38-cp38-macosx_10_14_x86_64.whl (235 kB)
Collecting jinja2

.... etc .....

Collecting pathlib>=1.0.1
  Using cached pathlib-1.0.1.tar.gz (49 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'error'
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [20 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/s3/ryybwwrx7cld88lzkc52k9p00000gn/T/pip-install-092y8_nj/pathlib_ee66713df26d450b818c2160435e1196/setup.py", line 6, in <module>
          setup(
        File "/Users/my_name/Library/r-miniconda/envs/r-reticulate/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 109, in setup
          _setup_distribution = dist = klass(attrs)
        File "/Users/my_name/Library/r-miniconda/envs/r-reticulate/lib/python3.8/site-packages/setuptools/dist.py", line 456, in __init__
          for ep in metadata.entry_points(group='distutils.setup_keywords'):
        File "/Users/my_name/Library/r-miniconda/envs/r-reticulate/lib/python3.8/site-packages/setuptools/_vendor/importlib_metadata/__init__.py", line 999, in entry_points
          return SelectableGroups.load(eps).select(**params)
        File "/Users/my_name/Library/r-miniconda/envs/r-reticulate/lib/python3.8/site-packages/setuptools/_vendor/importlib_metadata/__init__.py", line 449, in load
          ordered = sorted(eps, key=by_group)
        File "/Users/my_name/Library/r-miniconda/envs/r-reticulate/lib/python3.8/site-packages/setuptools/_vendor/importlib_metadata/__init__.py", line 997, in <genexpr>
          dist.entry_points for dist in unique(distributions())
        File "/Users/my_name/Library/r-miniconda/envs/r-reticulate/lib/python3.8/site-packages/setuptools/_vendor/importlib_metadata/__init__.py", line 609, in entry_points
          return EntryPoints._from_text_for(self.read_text('entry_points.txt'), self)
        File "/Users/my_name/Library/r-miniconda/envs/r-reticulate/lib/python3.8/site-packages/setuptools/_vendor/importlib_metadata/__init__.py", line 917, in read_text
          return self._path.joinpath(filename).read_text(encoding='utf-8')
      AttributeError: 'PosixPath' object has no attribute 'read_text'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
'''

#### After this error: 

'''
Activated conda python: /Users/my_name/Library/r-miniconda/envs/r-reticulate/bin/python
Collecting git+https://github.com/Techtonique/nnetsauce.git
  Cloning https://github.com/Techtonique/nnetsauce.git to /private/var/folders/s3/ryybwwrx7cld88lzkc52k9p00000gn/T/pip-req-build-4kofkdmi
  Running command git clone --filter=blob:none --quiet https://github.com/Techtonique/nnetsauce.git /private/var/folders/s3/ryybwwrx7cld88lzkc52k9p00000gn/T/pip-req-build-4kofkdmi
  Resolved https://github.com/Techtonique/nnetsauce.git to commit 6145d529cb4f2d1a890556c1d6f8733be7eaed8a
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'

etc......

Collecting pathlib>=1.0.1
  Using cached pathlib-1.0.1.tar.gz (49 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'error'
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [20 lines of output]
'''

#### And at the end:

'''
Error: le chargement du package ou de l'espace de noms a échoué pour ‘nnetsauce’ :
.onLoad a échoué dans loadNamespace() pour 'nnetsauce', détails :
  appel : NULL
  erreur : Error installing package(s): "'git+https://github.com/Techtonique/nnetsauce.git'"
Erreur : loading failed
Exécution arrêtée
ERROR: loading failed
* removing ‘/Library/Frameworks/R.framework/Versions/4.1/Resources/library/nnetsauce’
Message d'avis :
Dans i.p(...) :
  installation of package ‘/var/folders/s3/ryybwwrx7cld88lzkc52k9p00000gn/T//Rtmp1dUDN7/file12ec167d1ee5/nnetsauce_0.10.0.tar.gz’ had non-zero exit status
'''

**Comment by thierrymoudiki** [comment]
@samilotin, not sure __how to reproduce this error__: I'm using macOS Big Sur too. Can you use [this](https://rstudio.github.io/renv/articles/renv.html)? 

What happens when you try to install nnetsauce in a  _fresh_ environment like provided [in there](https://www.rstudio.com/products/cloud/).

PS: Using [Markdown](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax) would be really appreciated :) (increased readability)

**Comment by samilotin** [comment]
Howdy,

You say : "What happens when you try to install nnetsauce in a fresh environment like provided in there (https://www.rstudio.com/products/cloud/). »

I have tried and I get the same error :

What did I do?

1) installation of devtools
2) command: "> devtools::install_github("Techtonique/nnetsauce/R-package ») ».
     —> among others, reticulate is automatically installed
     —>  miniconda is automatically and successfully installed

3) here is the very end of the installation log of nnetsauce

*************************


MB/s eta 0:00:00
Collecting pathlib>=1.0.1
  Downloading pathlib-1.0.1.tar.gz (49 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 49.3/49.3 KB 4.0 MB/s eta 0:00:00
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'error'
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [20 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-aek4i4q7/pathlib_e21059edf7114241bac87437c7395ad9/setup.py", line 6, in <module>
          setup(
        File "/cloud/home/.local/share/r-miniconda/envs/r-reticulate/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 109, in setup
          _setup_distribution = dist = klass(attrs)
        File "/cloud/home/.local/share/r-miniconda/envs/r-reticulate/lib/python3.8/site-packages/setuptools/dist.py", line 456, in __init__
          for ep in metadata.entry_points(group='distutils.setup_keywords'):
        File "/cloud/home/.local/share/r-miniconda/envs/r-reticulate/lib/python3.8/site-packages/setuptools/_vendor/importlib_metadata/__init__.py", line 999, in entry_points
          return SelectableGroups.load(eps).select(**params)
        File "/cloud/home/.local/share/r-miniconda/envs/r-reticulate/lib/python3.8/site-packages/setuptools/_vendor/importlib_metadata/__init__.py", line 449, in load
          ordered = sorted(eps, key=by_group)
        File "/cloud/home/.local/share/r-miniconda/envs/r-reticulate/lib/python3.8/site-packages/setuptools/_vendor/importlib_metadata/__init__.py", line 997, in <genexpr>
          dist.entry_points for dist in unique(distributions())
        File "/cloud/home/.local/share/r-miniconda/envs/r-reticulate/lib/python3.8/site-packages/setuptools/_vendor/importlib_metadata/__init__.py", line 609, in entry_points
          return EntryPoints._from_text_for(self.read_text('entry_points.txt'), self)
        File "/cloud/home/.local/share/r-miniconda/envs/r-reticulate/lib/python3.8/site-packages/setuptools/_vendor/importlib_metadata/__init__.py", line 917, in read_text
          return self._path.joinpath(filename).read_text(encoding='utf-8')
      AttributeError: 'PosixPath' object has no attribute 'read_text'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
Error: package or namespace load failed for ‘nnetsauce’:
 .onLoad failed in loadNamespace() for 'nnetsauce', details:
  call: NULL
  error: Error installing package(s): "'git+https://github.com/Techtonique/nnetsauce.git'"
Error: loading failed
Execution halted

ERROR: loading failed
* removing ‘/cloud/lib/x86_64-pc-linux-gnu-library/4.1/nnetsauce’

Warning message:

In i.p(...) :

  installation of package ‘/tmp/RtmphLXQrG/fileda640bffbf/nnetsauce_0.10.0.tar.gz’ had non-zero exit status

**********************

It seems that nnetsauce does not install in a fresh linux environment either :-(

Sincerely,

FD

**Comment by samilotin** [comment]
Bonsoir,

Tout me porte à croire que vous maîtrisez parfaitement le français 😁 
L’installation de nnetsauce bute systématiquement sur la librairie python « pathlib ». J’ai donc pris le taureau par les cornes et j’ai décidé de la supprimer.

Dans l’environnement « r-reticulate » de miniconda j’ai donc desinstallé pathlib :

****** dans la console R **********
library(reticulate)
conda_remove(envname="r-reticulate", packages = "pathlib", conda = "auto »)
*************************************
La suppression se fait sans problème. Ensuite j’installe nnetsauce :

******* dans la console R***********
library(devtools)
devtools::install_github("Techtonique/nnetsauce/R-package »)
**************************************
et là, miracle, l’installation de la librairie R nnetsauce se fait sans problème.

En revanche, ce qui m’étonne, c’est que l’appelle de la librairie renvoie

*****************
> library(nnetsauce)
WARNING: Skipping nnetsauce as it is not installed.
*****************
et là, j’obtiens :

********* Console R **************
WARNING: Skipping nnetsauce as it is not installed.
Activated conda python: /Users/frederic/Library/r-miniconda/envs/r-reticulate/bin/python
Requirement already satisfied: numpy in /Users/frederic/Library/r-miniconda/envs/r-reticulate/lib/python3.8/site-packages (1.22.2)
Activated conda python: /Users/frederic/Library/r-miniconda/envs/r-reticulate/bin/python
Requirement already satisfied: rpy2 in /Users/frederic/Library/r-miniconda/envs/r-reticulate/lib/python3.8/site-packages (3.4.5)
Requirement already satisfied: pytz in /Users/frederic/Library/r-miniconda/envs/r-reticulate/lib/python3.8/site-packages (from rpy2) (2021.3)
Requirement already satisfied: tzlocal in /Users/frederic/Library/r-miniconda/envs/r-reticulate/lib/python3.8/site-packages (from rpy2) (4.1)
Requirement already satisfied: jinja2 in /Users/frederic/Library/r-miniconda/envs/r-reticulate/lib/python3.8/site-packages (from rpy2) (3.0.3)
Requirement already satisfied: cffi>=1.10.0 in /Users/frederic/Library/r-miniconda/envs/r-reticulate/lib/python3.8/site-packages (from rpy2) (1.15.0)
Requirement already satisfied: pycparser in /Users/frederic/Library/r-miniconda/envs/r-reticulate/lib/python3.8/site-packages (from cffi>=1.10.0->rpy2) (2.21)
Requirement already satisfied: MarkupSafe>=2.0 in /Users/frederic/Library/r-miniconda/envs/r-reticulate/lib/python3.8/site-packages (from jinja2->rpy2) (2.1.0)
Requirement already satisfied: backports.zoneinfo in /Users/frederic/Library/r-miniconda/envs/r-reticulate/lib/python3.8/site-packages (from tzlocal->rpy2) (0.2.1)
Requirement already satisfied: pytz-deprecation-shim in /Users/frederic/Library/r-miniconda/envs/r-reticulate/lib/python3.8/site-packages (from tzlocal->rpy2) (0.1.0.post0)
Requirement already satisfied: tzdata in /Users/frederic/Library/r-miniconda/envs/r-reticulate/lib/python3.8/site-packages (from pytz-deprecation-shim->tzlocal->rpy2) (2021.5)
Activated conda python: /Users/frederic/Library/r-miniconda/envs/r-reticulate/bin/python
Requirement already satisfied: scipy in /Users/frederic/Library/r-miniconda/envs/r-reticulate/lib/python3.8/site-packages (1.8.0)
Requirement already satisfied: numpy<1.25.0,>=1.17.3 in /Users/frederic/Library/r-miniconda/envs/r-reticulate/lib/python3.8/site-packages (from scipy) (1.22.2)
Activated conda python: /Users/frederic/Library/r-miniconda/envs/r-reticulate/bin/python
Requirement already satisfied: six in /Users/frederic/Library/r-miniconda/envs/r-reticulate/lib/python3.8/site-packages (1.16.0)
Activated conda python: /Users/frederic/Library/r-miniconda/envs/r-reticulate/bin/python
Requirement already satisfied: tqdm in /Users/frederic/Library/r-miniconda/envs/r-reticulate/lib/python3.8/site-packages (4.62.3)
Activated conda python: /Users/frederic/Library/r-miniconda/envs/r-reticulate/bin/python
Requirement already satisfied: sklearn in /Users/frederic/Library/r-miniconda/envs/r-reticulate/lib/python3.8/site-packages (0.0)
Requirement already satisfied: scikit-learn in /Users/frederic/Library/r-miniconda/envs/r-reticulate/lib/python3.8/site-packages (from sklearn) (1.0.2)
Requirement already satisfied: numpy>=1.14.6 in /Users/frederic/Library/r-miniconda/envs/r-reticulate/lib/python3.8/site-packages (from scikit-learn->sklearn) (1.22.2)
Requirement already satisfied: threadpoolctl>=2.0.0 in /Users/frederic/Library/r-miniconda/envs/r-reticulate/lib/python3.8/site-packages (from scikit-learn->sklearn) (3.1.0)
Requirement already satisfied: scipy>=1.1.0 in /Users/frederic/Library/r-miniconda/envs/r-reticulate/lib/python3.8/site-packages (from scikit-learn->sklearn) (1.8.0)
Requirement already satisfied: joblib>=0.11 in /Users/frederic/Library/r-miniconda/envs/r-reticulate/lib/python3.8/site-packages (from scikit-learn->sklearn) (1.1.0)
Activated conda python: /Users/frederic/Library/r-miniconda/envs/r-reticulate/bin/python
Collecting nnetsauce
  Using cached nnetsauce-0.10.0-cp38-cp38-macosx_10_15_x86_64.whl (653 kB)
Collecting black>=19.10b0
  Using cached black-22.1.0-cp38-cp38-macosx_10_9_x86_64.whl (1.3 MB)
Collecting snowballstemmer>=2.0.0
  Using cached snowballstemmer-2.2.0-py2.py3-none-any.whl (93 kB)
Collecting mkdocs>=1.1.2
  Using cached mkdocs-1.2.3-py3-none-any.whl (6.4 MB)
Collecting importlib-metadata>=1.7.0
  Using cached importlib_metadata-4.11.1-py3-none-any.whl (17 kB)
Collecting toml>=0.10.1
  Using cached toml-0.10.2-py2.py3-none-any.whl (16 kB)
Collecting jax>=0.1.72
  Using cached jax-0.3.1-py3-none-any.whl
Collecting lunr>=0.5.8
  Using cached lunr-0.6.1-py2.py3-none-any.whl (34 kB)
Collecting mkdocs-bootswatch>=1.1
  Using cached mkdocs_bootswatch-1.1-py2.py3-none-any.whl (560 kB)
Collecting requests>=2.24.0
  Using cached requests-2.27.1-py2.py3-none-any.whl (63 kB)
Collecting readme-renderer>=26.0
  Using cached readme_renderer-32.0-py3-none-any.whl (16 kB)
Collecting absl-py>=0.10.0
  Using cached absl_py-1.0.0-py3-none-any.whl (126 kB)
Collecting smmap>=3.0.4
  Using cached smmap-5.0.0-py3-none-any.whl (24 kB)
Collecting appdirs>=1.4.4
  Using cached appdirs-1.4.4-py2.py3-none-any.whl (9.6 kB)
Collecting pluggy>=0.13.1
  Using cached pluggy-1.0.0-py2.py3-none-any.whl (13 kB)
Collecting future>=0.18.2
  Using cached future-0.18.2-py3-none-any.whl
Collecting py>=1.10.0
  Using cached py-1.11.0-py2.py3-none-any.whl (98 kB)
Collecting flatbuffers>=1.12
  Using cached flatbuffers-2.0-py2.py3-none-any.whl (26 kB)
Collecting MarkupSafe>=1.1.1
  Using cached MarkupSafe-2.1.0-cp38-cp38-macosx_10_9_x86_64.whl (13 kB)
Collecting GitPython>=0.3.6
  Using cached GitPython-3.1.27-py3-none-any.whl (181 kB)
Collecting kiwisolver>=1.2.0
  Using cached kiwisolver-1.3.2-cp38-cp38-macosx_10_9_x86_64.whl (61 kB)
Collecting packaging>=20.4
  Using cached packaging-21.3-py3-none-any.whl (40 kB)
Collecting click>=7.1.2
  Using cached click-8.0.4-py3-none-any.whl (97 kB)
Collecting requests-toolbelt>=0.9.1
  Using cached requests_toolbelt-0.9.1-py2.py3-none-any.whl (54 kB)
Collecting cffi>=1.14.0
  Using cached cffi-1.15.0-cp38-cp38-macosx_10_9_x86_64.whl (178 kB)
Collecting Babel>=2.8.0
  Using cached Babel-2.9.1-py2.py3-none-any.whl (8.8 MB)
Collecting certifi>=2020.6.20
  Using cached certifi-2021.10.8-py2.py3-none-any.whl (149 kB)
Collecting pytz>=2020.1
  Using cached pytz-2021.3-py2.py3-none-any.whl (503 kB)
Collecting pathspec>=0.8.0
  Using cached pathspec-0.9.0-py2.py3-none-any.whl (31 kB)
Collecting attrs>=19.3.0
  Using cached attrs-21.4.0-py2.py3-none-any.whl (60 kB)
Collecting keras-autodoc>=0.5.1
  Using cached keras_autodoc-0.7.0-py3-none-any.whl
Collecting wcwidth>=0.2.5
  Using cached wcwidth-0.2.5-py2.py3-none-any.whl (30 kB)
Collecting opt-einsum>=3.3.0
  Using cached opt_einsum-3.3.0-py3-none-any.whl (65 kB)
Collecting sphinxcontrib-devhelp>=1.0.2
  Using cached sphinxcontrib_devhelp-1.0.2-py2.py3-none-any.whl (84 kB)
Collecting pathlib>=1.0.1
  Using cached pathlib-1.0.1-py3-none-any.whl
Collecting nose2>=0.9.2
  Using cached nose2-0.11.0-py2.py3-none-any.whl (144 kB)
Collecting chardet>=3.0.4
  Using cached chardet-4.0.0-py2.py3-none-any.whl (178 kB)
Collecting regex>=2020.7.14
  Using cached regex-2022.1.18-cp38-cp38-macosx_10_9_x86_64.whl (288 kB)
Collecting bleach>=3.3.0
  Using cached bleach-4.1.0-py2.py3-none-any.whl (157 kB)
Collecting docutils>=0.16
  Using cached docutils-0.18.1-py2.py3-none-any.whl (570 kB)
Collecting gitdb>=4.0.5
  Using cached gitdb-4.0.9-py3-none-any.whl (63 kB)
Collecting sphinxcontrib-jsmath>=1.0.1
  Using cached sphinxcontrib_jsmath-1.0.1-py2.py3-none-any.whl (5.1 kB)
Collecting alabaster>=0.7.12
  Using cached alabaster-0.7.12-py2.py3-none-any.whl (14 kB)
Collecting pytest>=5.4.3
  Using cached pytest-7.0.1-py3-none-any.whl (296 kB)
Collecting Pygments>=2.7.4
  Using cached Pygments-2.11.2-py3-none-any.whl (1.1 MB)
Collecting threadpoolctl>=2.0.0
  Using cached threadpoolctl-3.1.0-py3-none-any.whl (14 kB)
Collecting python-dateutil>=2.8.1
  Using cached python_dateutil-2.8.2-py2.py3-none-any.whl (247 kB)
Collecting tornado>=6.0.4
  Using cached tornado-6.1-cp38-cp38-macosx_10_9_x86_64.whl (416 kB)
Collecting pycparser>=2.20
  Using cached pycparser-2.21-py2.py3-none-any.whl (118 kB)
Collecting sphinxcontrib-serializinghtml>=1.1.4
  Using cached sphinxcontrib_serializinghtml-1.1.5-py2.py3-none-any.whl (94 kB)
Collecting twine>=3.2.0
  Using cached twine-3.8.0-py3-none-any.whl (36 kB)
Collecting more-itertools>=8.4.0
  Using cached more_itertools-8.12.0-py3-none-any.whl (54 kB)
Collecting sphinx-rtd-theme>=0.5.0
  Using cached sphinx_rtd_theme-1.0.0-py2.py3-none-any.whl (2.8 MB)
Collecting urllib3>=1.21.1
  Using cached urllib3-1.26.8-py2.py3-none-any.whl (138 kB)
Collecting cycler>=0.10.0
  Using cached cycler-0.11.0-py3-none-any.whl (6.4 kB)
Collecting scikit-learn>=0.18.0
  Using cached scikit_learn-1.0.2-cp38-cp38-macosx_10_13_x86_64.whl (7.9 MB)
Collecting webencodings>=0.5.1
  Using cached webencodings-0.5.1-py2.py3-none-any.whl (11 kB)
Collecting scipy>=0.19.0
  Using cached scipy-1.8.0-cp38-cp38-macosx_12_0_universal2.macosx_10_9_x86_64.whl (55.3 MB)
Collecting idna>=2.10
  Using cached idna-3.3-py3-none-any.whl (61 kB)
Collecting imagesize>=1.2.0
  Using cached imagesize-1.3.0-py2.py3-none-any.whl (5.2 kB)
Collecting sphinxcontrib-qthelp>=1.0.3
  Using cached sphinxcontrib_qthelp-1.0.3-py2.py3-none-any.whl (90 kB)
Collecting rfc3986>=1.4.0
  Using cached rfc3986-2.0.0-py2.py3-none-any.whl (31 kB)
Collecting jaxlib>=0.1.51
  Using cached jaxlib-0.3.0-cp38-none-macosx_10_9_x86_64.whl (67.2 MB)
Collecting nltk>=3.5
  Using cached nltk-3.7-py3-none-any.whl (1.5 MB)
Collecting joblib>=0.14.0
  Using cached joblib-1.1.0-py2.py3-none-any.whl (306 kB)
Collecting Pillow>=8.2.0
  Using cached Pillow-9.0.1-cp38-cp38-macosx_10_10_x86_64.whl (3.0 MB)
Collecting sphinxcontrib-applehelp>=1.0.2
  Using cached sphinxcontrib_applehelp-1.0.2-py2.py3-none-any.whl (121 kB)
Collecting tqdm>=4.48.1
  Using cached tqdm-4.62.3-py2.py3-none-any.whl (76 kB)
Collecting cython>=0.29.21
  Using cached Cython-0.29.28-py2.py3-none-any.whl (983 kB)
Collecting numpy>=1.13.0
  Using cached numpy-1.22.2-cp38-cp38-macosx_10_14_x86_64.whl (17.6 MB)
Collecting zipp>=3.1.0
  Using cached zipp-3.7.0-py3-none-any.whl (5.3 kB)
Collecting six>=1.15.0
  Using cached six-1.16.0-py2.py3-none-any.whl (11 kB)
Collecting Markdown>=3.2.2
  Using cached Markdown-3.3.6-py3-none-any.whl (97 kB)
Collecting Jinja2>=2.11.3
  Using cached Jinja2-3.0.3-py3-none-any.whl (133 kB)
Collecting pkginfo>=1.5.0.1
  Using cached pkginfo-1.8.2-py2.py3-none-any.whl (26 kB)
Collecting typed-ast>=1.4.1
  Using cached typed_ast-1.5.2-cp38-cp38-macosx_10_9_x86_64.whl (222 kB)
Collecting sphinxcontrib-htmlhelp>=1.0.3
  Using cached sphinxcontrib_htmlhelp-2.0.0-py2.py3-none-any.whl (100 kB)
Collecting Sphinx>=3.1.2
  Using cached Sphinx-4.4.0-py3-none-any.whl (3.1 MB)
Collecting PyYAML>=5.4
  Using cached PyYAML-6.0-cp38-cp38-macosx_10_9_x86_64.whl (192 kB)
Collecting colorama>=0.4.3
  Using cached colorama-0.4.4-py2.py3-none-any.whl (16 kB)
Collecting pypi-publisher>=0.0.4
  Using cached pypi_publisher-0.0.4-py2.py3-none-any.whl
Collecting coverage>=5.2
  Using cached coverage-6.3.2-cp38-cp38-macosx_10_9_x86_64.whl (183 kB)
Collecting tzlocal>=2.1
  Using cached tzlocal-4.1-py3-none-any.whl (19 kB)
Collecting keyring>=21.4.0
  Using cached keyring-23.5.0-py3-none-any.whl (33 kB)
Collecting livereload>=2.6.3
  Using cached livereload-2.6.3-py2.py3-none-any.whl
Collecting matplotlib>=3.3.1
  Using cached matplotlib-3.5.1-cp38-cp38-macosx_10_9_x86_64.whl (7.3 MB)
Collecting pyparsing>=2.4.7
  Using cached pyparsing-3.0.7-py3-none-any.whl (98 kB)
Collecting platformdirs>=2
  Using cached platformdirs-2.5.1-py3-none-any.whl (14 kB)
Collecting tomli>=1.1.0
  Using cached tomli-2.0.1-py3-none-any.whl (12 kB)
Collecting typing-extensions>=3.10.0.0
  Using cached typing_extensions-4.1.1-py3-none-any.whl (26 kB)
Collecting mypy-extensions>=0.4.3
  Using cached mypy_extensions-0.4.3-py2.py3-none-any.whl (4.5 kB)
Collecting black>=19.10b0
  Using cached black-20.8b1-py3-none-any.whl
Collecting fonttools>=4.22.0
  Using cached fonttools-4.29.1-py3-none-any.whl (895 kB)
Collecting pyyaml-env-tag>=0.1
  Using cached pyyaml_env_tag-0.1-py3-none-any.whl (3.9 kB)
Collecting watchdog>=2.0
  Using cached watchdog-2.1.6-cp38-cp38-macosx_10_9_x86_64.whl (85 kB)
Collecting ghp-import>=1.0
  Using cached ghp_import-2.0.2-py3-none-any.whl (11 kB)
Collecting mergedeep>=1.3.4
  Using cached mergedeep-1.3.4-py3-none-any.whl (6.4 kB)
Collecting GitPython>=0.3.6
  Using cached GitPython-0.3.6-py3-none-any.whl
Collecting iniconfig
  Using cached iniconfig-1.1.1-py2.py3-none-any.whl (5.0 kB)
Collecting charset-normalizer~=2.0.0
  Using cached charset_normalizer-2.0.12-py3-none-any.whl (39 kB)
Collecting docutils>=0.16
  Using cached docutils-0.17.1-py2.py3-none-any.whl (575 kB)
Collecting backports.zoneinfo
  Using cached backports.zoneinfo-0.2.1-cp38-cp38-macosx_10_14_x86_64.whl (35 kB)
Collecting pytz-deprecation-shim
  Using cached pytz_deprecation_shim-0.1.0.post0-py2.py3-none-any.whl (15 kB)
Collecting tzdata
  Using cached tzdata-2021.5-py2.py3-none-any.whl (339 kB)
Installing collected packages: zipp, six, pyparsing, webencodings, urllib3, smmap, PyYAML, pytz, python-dateutil, packaging, MarkupSafe, importlib-metadata, idna, charset-normalizer, certifi, watchdog, tzdata, typing-extensions, typed-ast, toml, sphinxcontrib-serializinghtml, sphinxcontrib-qthelp, sphinxcontrib-jsmath, sphinxcontrib-htmlhelp, sphinxcontrib-devhelp, sphinxcontrib-applehelp, snowballstemmer, requests, regex, pyyaml-env-tag, Pygments, pathspec, numpy, mypy-extensions, mergedeep, Markdown, Jinja2, imagesize, gitdb, ghp-import, docutils, click, bleach, backports.zoneinfo, Babel, appdirs, alabaster, tqdm, tornado, tomli, threadpoolctl, Sphinx, scipy, rfc3986, requests-toolbelt, readme-renderer, pytz-deprecation-shim, pycparser, py, pluggy, pkginfo, Pillow, opt-einsum, mkdocs, kiwisolver, keyring, joblib, iniconfig, GitPython, fonttools, flatbuffers, cycler, coverage, colorama, black, attrs, absl-py, wcwidth, tzlocal, twine, sphinx-rtd-theme, scikit-learn, pytest, pypi-publisher, pathlib, nose2, nltk, more-itertools, mkdocs-bootswatch, matplotlib, lunr, livereload, keras-autodoc, jaxlib, jax, future, cython, chardet, cffi, nnetsauce
Successfully installed Babel-2.9.1 GitPython-0.3.6 Jinja2-3.0.3 Markdown-3.3.6 MarkupSafe-2.1.0 Pillow-9.0.1 PyYAML-6.0 Pygments-2.11.2 Sphinx-4.4.0 absl-py-1.0.0 alabaster-0.7.12 appdirs-1.4.4 attrs-21.4.0 backports.zoneinfo-0.2.1 black-20.8b1 bleach-4.1.0 certifi-2021.10.8 cffi-1.15.0 chardet-4.0.0 charset-normalizer-2.0.12 click-8.0.4 colorama-0.4.4 coverage-6.3.2 cycler-0.11.0 cython-0.29.28 docutils-0.17.1 flatbuffers-2.0 fonttools-4.29.1 future-0.18.2 ghp-import-2.0.2 gitdb-4.0.9 idna-3.3 imagesize-1.3.0 importlib-metadata-4.11.1 iniconfig-1.1.1 jax-0.3.1 jaxlib-0.3.0 joblib-1.1.0 keras-autodoc-0.7.0 keyring-23.5.0 kiwisolver-1.3.2 livereload-2.6.3 lunr-0.6.1 matplotlib-3.5.1 mergedeep-1.3.4 mkdocs-1.2.3 mkdocs-bootswatch-1.1 more-itertools-8.12.0 mypy-extensions-0.4.3 nltk-3.7 nnetsauce-0.10.0 nose2-0.11.0 numpy-1.22.2 opt-einsum-3.3.0 packaging-21.3 pathlib-1.0.1 pathspec-0.9.0 pkginfo-1.8.2 pluggy-1.0.0 py-1.11.0 pycparser-2.21 pyparsing-3.0.7 pypi-publisher-0.0.4 pytest-7.0.1 python-dateutil-2.8.2 pytz-2021.3 pytz-deprecation-shim-0.1.0.post0 pyyaml-env-tag-0.1 readme-renderer-32.0 regex-2022.1.18 requests-2.27.1 requests-toolbelt-0.9.1 rfc3986-2.0.0 scikit-learn-1.0.2 scipy-1.8.0 six-1.16.0 smmap-5.0.0 snowballstemmer-2.2.0 sphinx-rtd-theme-1.0.0 sphinxcontrib-applehelp-1.0.2 sphinxcontrib-devhelp-1.0.2 sphinxcontrib-htmlhelp-2.0.0 sphinxcontrib-jsmath-1.0.1 sphinxcontrib-qthelp-1.0.3 sphinxcontrib-serializinghtml-1.1.5 threadpoolctl-3.1.0 toml-0.10.2 tomli-2.0.1 tornado-6.1 tqdm-4.62.3 twine-3.8.0 typed-ast-1.5.2 typing-extensions-4.1.1 tzdata-2021.5 tzlocal-4.1 urllib3-1.26.8 watchdog-2.1.6 wcwidth-0.2.5 webencodings-0.5.1 zipp-3.7.0
**********************

Est-ce que c’est normal ? Si oui, je trouve ça assez déroutant en tant qu’utilisateur lambda. Peut-être faudrait-il le dire dans la documentation ?

A part ça, j’ai testé les exemples fournis dans la documentation et tout fonctionne parfaitement.

Cordialement,

Frédéric Dupont

**Comment by thierrymoudiki** [comment]
@samilotin: "Miracle" ? non :) Content de savoir que tout fonctionne correctement, malgré les warnings un peu déroutants. J'ai les mêmes, je vais y jeter un oeil. N'hésitez pas, si vous avez des remarques/observations.

**Comment by samilotin** [comment]
Bonsoir,

Ci-joint, au format pdf (mais écrit en Markdown 😇) le résultat des tests sur les exemples fournis et une réflexion sur le caractère miraculeux de l’installation de nnetsauce. Je vous rappelle que je me mets dans la position de l’utilisateur lambda qui installe et teste un programme en espérant qu’il fonctionne « out of the box ».

En espérant que cela vous aidera à améliorer la librairie R.

Cordialement,

Frédéric Dupont

**Comment by thierrymoudiki** [comment]
@samilotin merci! Où se trouve le fichier pdf? 

"Je vous rappelle que je me mets dans la position de l’utilisateur lambda qui installe et teste un programme en espérant qu’il fonctionne « out of the box »" C'est ce vers quoi on devrait tendre sur la version R, mais il y a parfois des différences/spécificités selon les OS.

**Comment by samilotin** [comment]
Bonjour,

Le fichier pdf était  un fichier joint au mail. Je le reposte.

Cordialement,

fd

**Comment by thierrymoudiki** [comment]
@samilotin pas reçu.
